### ISSUE TITLE
Error output

### ISSUE THREAD

**Issue by BAD7777** [buape/ActivityRoles#18]
**Problem name:** Error "DiscordSRV encountered an unknown Discord error: 10007: Unknown Member" when using the plugin with version git-Purpur-2056 (MC: 1.20.1)

**Description of the problem:**

When using the Discords plugin with the server version git-Purpur-2056 (MC: 1.20.1), an error occurs that is constantly displayed in the console. The error has the following text: "DiscordSRV encountered an unknown Discord error: 10007: Unknown Member."

**Steps to reproduce:**

Install the server with version git-Purpur-2056 (MC: 1.20.1).

Install and configure the DiscordSRV plugin.

Start the server and pay attention to the console.

**Expected behavior:**

The DiscordSRV plugin should work without errors and not display the message "DiscordSRV encountered an unknown Discord error: 10007: Unknown Member" in the console.

**Actual behavior:**

The DiscordSRV plugin outputs the error "DiscordSRV encountered an unknown Discord error: 10007: Unknown Member" in the console.

![image](https://github.com/buape/ActivityRoles/assets/129652614/48ed73fd-77f6-4a2d-82fa-919d5ef1b261)

**Comment by thewilloftheshadow** [comment]
Fixed in https://github.com/buape/ActivityRoles/commit/11d8b4ef85c975dc18b75738556ffc692b104ba2
